import type { DashboardTheme } from '@/themes/types'
import { structureTokens } from '@/themes/structure'

/**
 * Палитра и визуал карточек/панелей один в один из CalMusLast.
 * Структура экрана не меняется: нет «Целей», «Сунны» и аватарки.
 * Градиентов намазов нет — в исходнике карточки белые, плашки серые.
 */
export const classicTheme: DashboardTheme = {
  id: 'theme-2',
  label: 'Тема 2',
  trackerBars: [
    { background: '#8c59d0', shadow: 'none' },
    { background: '#9d6ad6', shadow: 'none' },
  ],
  tokens: {
    ...structureTokens,
    'page-bg': '#8c59d0',
    'page-image': 'linear-gradient(to bottom right, #8c59d0, #9d6ad6, #7c4cc0)',
    'page-repeat': 'no-repeat',
    'page-size': 'cover',
    'page-blend': 'normal',
    'texture-image': 'none',
    'texture-opacity': '0',
    'texture-blend': 'normal',
    'text': '#000000',
    'muted': '#111827',
    'panel-bg': 'rgba(248, 250, 252, 0.95)',
    'panel-border': '2px solid rgba(226, 232, 240, 0.5)',
    'panel-radius': '1rem',
    'panel-shadow': '0 10px 15px -3px rgba(108, 62, 244, 0.2), 0 4px 6px -2px rgba(108, 62, 244, 0.15)',
    'panel-blur': '4px',
    'bottom-panel-bg': 'rgba(248, 250, 252, 0.95)',
    'heading-color': '#8c59d0',
    'heading-size': '16px',
    'heading-weight': '600',
    'heading-tracking': '0.025em',
    'heading-transform': 'none',
    'clock-size': '1.25rem',
    'clock-weight': '800',
    'clock-tracking': '0',
    'clock-color': '#111827',
    'calendar-width': '24rem',
    'calendar-header-bg': '#9d6ad6',
    'calendar-header-color': '#ffffff',
    'calendar-header-size': '1.125rem',
    'calendar-header-weight': '700',
    'calendar-header-radius': '1rem',
    'nav-btn-bg': 'transparent',
    'nav-btn-color': '#ffffff',
    'weekday-color': '#374151',
    'weekday-weight': '600',
    'weekday-divider': '1px solid rgba(0, 0, 0, 0.2)',
    'day-color': '#111827',
    'day-outside': '#9ca3af',
    'day-radius': '0.25rem',
    'today-bg': '#dbeafe',
    'today-color': '#111827',
    'selected-bg': '#9d6ad6',
    'selected-color': '#ffffff',
    'prayer-title-font': "Cairo, Poppins, sans-serif",
    'prayer-title-size': '1.25rem',
    'prayer-title-weight': '600',
    'prayer-title-tracking': '0',
    'prayer-title-transform': 'none',
    'prayer-title-color': '#000000',
    'prayer-time-color': '#000000',
    'prayer-time-size': '1rem',
    'prayer-time-weight': '500',
    'card-font': 'Poppins, sans-serif',
    'card-font-size': '0.875rem',
    'card-font-weight': '500',
    'card-tracking': '0',
    'card-bg': '#ffffff',
    'card-border': '2px solid #323232',
    'card-border-bottom': '4px solid #323232',
    'card-shadow': 'none',
    'card-blur': '0px',
    'row-height': '2rem',
    'row-radius': '0.5rem',
    'row-margin': '0.5rem 0.5rem 0',
    'fixed-row-bg': '#f3f4f6',
    'fixed-row-color': '#000000',
    'fixed-row-border': '1px solid #8c59d0',
    'fixed-time-color': '#000000',
    'task-row-bg': 'transparent',
    'task-row-color': '#000000',
    'task-row-border': '1px solid #8c59d0',
    'task-dash': '#5b21b6',
    'task-time-color': '#000000',
    'editor-bg': 'rgba(255, 255, 255, 0.1)',
    'editor-border': '1px solid #8c59d0',
    'editor-color': '#000000',
    'editor-radius': '0.5rem',
    'add-btn-bg': '#8c59d0',
    'add-btn-color': '#ffffff',
    'add-btn-border': 'none',
    'add-btn-hover': 'rgba(140, 89, 208, 0.8)',
    'add-btn-hover-color': '#ffffff',
    'add-btn-hover-border': 'transparent',
    'note-bg': 'rgba(255, 255, 255, 0.7)',
    'note-color': '#111827',
    'note-ring': 'rgba(255, 255, 255, 0.5)',
    'note-btn-bg': '#8c59d0',
    'note-btn-color': '#ffffff',
    'note-btn-hover': '#7c4cc0',
    'note-btn-weight': '500',
    'placeholder': '#9ca3af',
    'badge-border': '#8c59d0',
    'status-done': '#22c55e',
    'status-overdue': '#ef4444',
    'scrollbar-thumb': '#8c59d0',
    'scrollbar-track': 'rgba(255, 255, 255, 0.08)',
    'card-scrollbar': '#8c59d0',
  },
}
