/** Размеры, шрифты и форма из многоцветной темы. Общие для всех палитр. */
export const structureTokens: Record<string, string> = {
  'font-family': "Poppins, -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif",
  'stack-gap': '1rem',
  'panel-radius': '1.5rem',
  'panel-blur': '12px',
  'heading-size': '15px',
  'heading-weight': '400',
  'heading-tracking': '0.12em',
  'heading-transform': 'uppercase',
  'clock-size': '40px',
  'clock-weight': '400',
  'clock-tracking': '0.12em',
  'calendar-width': '20rem',
  'day-radius': '9999px',
  'day-size': '1.75rem',
  'prayer-title-font': 'Inter, sans-serif',
  'prayer-title-size': '16px',
  'prayer-title-weight': '400',
  'prayer-title-tracking': '0.12em',
  'prayer-title-transform': 'uppercase',
  'prayer-time-size': '16px',
  'prayer-time-weight': '400',
  'card-font': 'Inter, sans-serif',
  'card-font-size': '15px',
  'card-tracking': '0.12em',
  'card-radius': '1rem',
  'row-height': '2.25rem',
  'row-radius': '0.75rem',
  'editor-radius': '0.75rem',
  'fixed-row-border': 'none',
}
